# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: esm-regions

channels:
  - conda-forge # pypsa
  - bioconda # snakemake
  - http://conda.anaconda.org/gurobi # gurobi

dependencies:
  - python
  - pip
  - pypsa>=0.17.1
  - jupyterlab

  # Dependencies of the workflow itself
  - scikit-learn
  - snakemake-minimal<=5.24.2 # until https://github.com/snakemake/snakemake/issues/635 closed
  - yaml
  - numpy<=1.19.0 # otherwise macos fails

  # Second order dependencies which should really be deps of atlite
  - xarray
  - netcdf4

  # Include ipython so that one does not inadvertently drop out of the conda
  # environment by calling ipython
  - ipython

  # GIS dependencies:
  - cartopy
  - geopandas

  # Solvers
  - gurobi:gurobi # until https://github.com/conda-forge/pypsa-feedstock/issues/4 closed

  - pip:
    - vresutils==0.3.1
    - descartes

  # includes implementation of max-p-regions heuristic.
  # (both from conda-forge)
  - region
  - libpysal